config:
  target: 'https://api.stahc.uk'  # Your server address
  phases:
    - duration: 60  # Test duration in seconds
      arrivalRate: 10  # 10 users per second
scenarios:
  # Scenario for registering and logging in users
  - name: "User registration and login"
    flow:
      - post:
          url: "/auth/signup"
          json:
            username: "user{{ $loop }}@example.com"
            email: "user{{ $loop }}@example.com"
            password: "password123"
          capture:
            - json: "$.token"  # Capture the token for further use
              as: "token" 
      - post:
          url: "/auth/login"
          json:
            email: "user{{ $loop }}@example.com"
            password: "password123"
          capture:
            - json: "$.token"  # Capture the token after login
              as: "token"
  
  - name: "User sends a message"
    flow:
      - post:
          url: "/chat/send"  # Endpoint for sending messages
          json:
            content: "Hello from user {{ userId }}"
            userId: "{{ userId }}"
          capture:
            - json: "$.messageId"  # Capture the message ID for further validation
              as: "messageId" # Specify how to store the captured value

  - name: "User joins a chat room"
    flow:
      - post:
          url: "/rooms/join"  # Endpoint for joining a chat room
          json:
            roomId: "{{ roomId }}"
            userId: "{{ userId }}"
          capture:
            - json: "$.roomId"  # Capture the room ID for validation
              as: "joinedRoomId"  # Specify how to store the captured value

  - name: "User loads chat history"
    flow:
      - get:
          url: "/chat/rooms/{{ roomId }}/logs"  # Endpoint for loading chat logs
          headers:
            Authorization: "Bearer {{ token }}"  # Use a valid token
          capture:
            - json: "$.messages"  # Capture messages for validation
              as: "chatMessages"

  - name: "Simulate multiple users sending messages"
    flow:
      - loop:
        - post:
            url: "/chat/send"
            json:
              content: "Message {{ $loopCount }} from user {{ userId }}"
              userId: "{{ userId }}"
        count: 5  # Each user sends 5 messages

  - name: "Retrieve chat logs"
    flow:
      - get:
          url: "/chat/rooms/1/logs"
