http:
  host: '${SERVER_DOMAIN}'
  port: ${SERVER_PORT}

db:
  postgres:
    url: '${DATABASE_HOST}'
    port: ${DATABASE_PORT}
    database: '${DATABASE_NAME}'
    username: '${DATABASE_USERNAME}'
    password: '${DATABASE_PASSWORD}'

  redis:
    host: '${REDIS_HOST}'
    port: ${REDIS_PORT}

  mysql:
    url: 'localhost' #${DATABASE_HOST}
    #    host: 'localhost'
    port: 5432 #${DATABASE_PORT}
    database: 'chatmysql'
