name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        env:
          APP_NAME: ${{ secrets.APP_NAME }}
          DOCKER_REPO: ${{ secrets.DOCKER_REPO}}
        run: |
          # Build Docker image
          echo "Building Docker image: $DOCKER_REPO/$APP_NAME:$DOCKER_TAG"
          docker build -t $DOCKER_REPO/$APP_NAME:$DOCKER_TAG .
          
          # Push to Docker Hub
          echo "Pushing Docker image to registry..."
          docker push $DOCKER_REPO/$APP_NAME:$DOCKER_TAG
          
          # Verify image
          echo "Verifying pushed image..."
          docker images | grep $APP_NAME

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-2

                                                                
        run: |
          echo "$SSH_PRIVATE_KEY" > private_key.pem
          chmod 600 private_key.pem
          ssh -i private_key.pem -o StrictHostKeyChecking=no $EC2_USER@$EC2_HOST "bash /opt/chat-service/scripts/deploy.sh"
          rm private_key.pem
