name: Deploy to EC2 with Docker

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        run: |
          docker buildx build --platform linux/amd64 -t your-dockerhub-username/your-app-name:latest .
          docker push your-dockerhub-username/your-app-name:latest

      - name: Install SSH key
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Transfer .env.prod file
        run: |
          scp -o StrictHostKeyChecking=no -i ${{ secrets.SSH_PRIVATE_KEY }} .env.prod ec2-user@${{ secrets.EC2_HOST }}:/path/to/your/project/.env.prod

      - name: Deploy to EC2
        env:
          EC2_USER: 'ec2-user'
          EC2_HOST: ${{ secrets.EC2_HOST }}
          DOCKER_IMAGE: 'your-dockerhub-username/your-app-name:latest'
        run: |
          ssh -o StrictHostKeyChecking=no $EC2_USER@$EC2_HOST << EOF
            cd /path/to/your/project
            docker pull $DOCKER_IMAGE
            docker-compose --env-file .env.prod down
            docker-compose --env-file .env.prod up -d
          EOF
